/**
 * Helpers for maintaining the tools directory: example rendering, verification and the index.
 * Used by `wirebay tools verify/index`, the snapshot tests and `npm run gen:docs`.
 * @module
 */

import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import type { AdapterFactory } from "../adapters/AdapterFactory.ts";
import { WirebayPaths } from "../platform/WirebayPaths.ts";
import { SchemaValidator } from "../schema/SchemaValidator.ts";
import { EntryRenderer } from "../sync/EntryRenderer.ts";
import type { Tool } from "../tools/Tool.ts";
import type { ScopeName, ToolManifest } from "../types.ts";

/** The result of verifying one tool. */
export interface VerifyResult {
  tool: string;
  ok: boolean;
  checks: { name: string; ok: boolean; detail?: string }[];
}

/** Example rendering, verification and index generation for `tools/`. */
export class ToolDirectory {
  /** Servers used in the examples. */
  static readonly exampleServers = ["github", "netlify"];
  private static readonly extensions: Record<ToolManifest["format"], string> = { json: "json", jsonc: "json", toml: "toml", yaml: "yaml" };

  private readonly adapters: AdapterFactory;
  private readonly validator = new SchemaValidator();

  constructor(adapters: AdapterFactory) {
    this.adapters = adapters;
  }

  /** File name of a tool's example for a scope, e.g. `user.json`. */
  static exampleFileName(tool: Tool, scope: ScopeName): string {
    return `${scope}.${ToolDirectory.extensions[tool.format]}`;
  }

  /** The example config text: placeholders (`{{NODE}}`, `{{WIREBAY_CLI}}`) keep it identical on every machine. */
  renderExample(tool: Tool, scope: ScopeName): string {
    const renderer = new EntryRenderer({
      mode: scope === "project" ? "portable" : "absolute",
      nodePath: "{{NODE}}",
      cliPath: "{{WIREBAY_CLI}}",
      os: "linux",
    });
    const set = Object.fromEntries(ToolDirectory.exampleServers.map((s) => [s, renderer.render(s, tool)]));
    const target = { tool, scope, file: `example.${ToolDirectory.extensions[tool.format]}` };
    const empty = { text: "", exists: false, entries: {}, locked: new Set<string>() };
    return this.adapters.for(tool).render(target, empty, { set, remove: [] });
  }

  /** Check a tool's manifest against the schema and its examples against the renderer. */
  verify(tool: Tool): VerifyResult {
    const checks: VerifyResult["checks"] = [];
    const raw: ToolManifest = { ...tool.manifest };
    delete raw.source;
    const errors = this.validator.validate("tool", raw);
    checks.push({ name: "manifest matches schema", ok: !errors.length, detail: errors.join("; ") || undefined });
    for (const scope of tool.scopes) {
      const name = ToolDirectory.exampleFileName(tool, scope);
      const file = WirebayPaths.packagePath("tools", tool.id, "examples", name);
      if (!existsSync(file)) {
        checks.push({ name: `examples/${name} exists`, ok: false, detail: "run `npm run gen:docs` to create it" });
        continue;
      }
      const same = readFileSync(file, "utf8").replace(/\r\n/g, "\n") === this.renderExample(tool, scope);
      checks.push({
        name: `renders like examples/${name}`,
        ok: same,
        detail: same ? undefined : "output changed; review and run `npm run gen:docs`",
      });
    }
    const verified = tool.manifest.lastVerified;
    const age = verified ? Math.floor((Date.now() - Date.parse(verified)) / 86_400_000) : Infinity;
    checks.push({ name: "verified in the last 90 days", ok: age <= 90, detail: verified ?? "never" });
    return { tool: tool.id, ok: checks.every((c) => c.ok || c.name.startsWith("verified")), checks };
  }

  /** Markdown for `tools/INDEX.md`. */
  static indexMarkdown(tools: Tool[]): string {
    const rows = tools.map((t) => {
      const docs = t.manifest.docs?.mcp ? `[docs](${t.manifest.docs.mcp})` : "";
      return `| [${t.name}](${t.id}/GUIDE.md) | \`${t.id}\` | ${t.aliases.map((a) => `\`${a}\``).join(" ")} | ${t.format} | ${t.scopes.join(", ")} | ${t.status} | ${t.manifest.lastVerified ?? "never"} | ${docs} |`;
    });
    return [
      "# Tools directory",
      "",
      "<!-- Generated by `npm run gen:docs` from tools/*/tool.json. Do not edit by hand. -->",
      "",
      "Every AI tool wirebay can write MCP config for. Each folder has a `tool.json` manifest,",
      "a `GUIDE.md` with setup and quirks, and `examples/` of what wirebay writes.",
      "",
      "| Tool | Id | Aliases | Format | Scopes | Status | Last verified | Official docs |",
      "|---|---|---|---|---|---|---|---|",
      ...rows,
      "",
      "Missing a tool? See [Add a tool](../docs/contributing/add-a-tool.md). It is usually just JSON and Markdown.",
      "",
    ].join("\n");
  }

  /** Days since a `YYYY-MM-DD` date (Infinity when missing or invalid). */
  static daysSince(date: string | undefined, now = new Date()): number {
    if (!date || !/^\d{4}-\d{2}-\d{2}$/.test(date)) return Infinity;
    return Math.floor((now.getTime() - new Date(date + "T00:00:00Z").getTime()) / 86_400_000);
  }

  /** Path of a tool's folder in the package. */
  static folder(toolId: string): string {
    return path.join(WirebayPaths.packagePath("tools"), toolId);
  }
}
