// Tools-directory helpers shared by the CLI (`tools verify`, `tools index`), tests and scripts:
// render a sample entry with placeholders and compare it with tools/<id>/examples/.

import { existsSync, readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { adapterFor } from "../adapters/index.ts";
import { packagePaths } from "./paths.ts";
import { renderEntry, type RenderContext } from "./render.ts";
import type { ScopeName, ToolManifest } from "./types.ts";
import { validateAgainst } from "./validate.ts";

/** Placeholders used in examples/ so they are identical on every machine. */
export function exampleContext(os: RenderContext["os"] = "linux", mode: RenderContext["mode"] = "absolute"): RenderContext {
  return { mode, nodePath: "{{NODE}}", cliPath: "{{WIREBAY_CLI}}", os };
}

export const EXAMPLE_SERVERS = ["github", "netlify"];

const EXT: Record<ToolManifest["format"], string> = { json: "json", jsonc: "json", toml: "toml", yaml: "yaml" };

/** File name of the example for a scope, e.g. user.json or project.json. */
export function exampleFileName(tool: ToolManifest, scope: ScopeName): string {
  return `${scope}.${EXT[tool.format]}`;
}

/** Render the example config text for a tool and scope. */
export function renderExample(tool: ToolManifest, scope: ScopeName): string {
  const ctx = exampleContext("linux", scope === "project" ? "portable" : "absolute");
  const set = Object.fromEntries(EXAMPLE_SERVERS.map((s) => [s, renderEntry(s, tool, ctx)]));
  const target = { tool, scope, file: `example.${EXT[tool.format]}` };
  const empty = { text: "", exists: false, entries: {}, locked: new Set<string>() };
  return adapterFor(tool).render(target, empty, { set, remove: [] });
}

export interface VerifyResult {
  tool: string;
  ok: boolean;
  checks: { name: string; ok: boolean; detail?: string }[];
}

export function verifyTool(tool: ToolManifest): VerifyResult {
  const checks: VerifyResult["checks"] = [];
  const { source: _s, ...raw } = tool;
  const errors = validateAgainst("tool", raw);
  checks.push({ name: "manifest matches schema", ok: !errors.length, detail: errors.join("; ") || undefined });
  for (const scope of Object.keys(tool.configs) as ScopeName[]) {
    const file = path.join(packagePaths.tools, tool.id, "examples", exampleFileName(tool, scope));
    if (!existsSync(file)) {
      checks.push({ name: `examples/${exampleFileName(tool, scope)} exists`, ok: false, detail: "run `npm run gen:docs` to create it" });
      continue;
    }
    const same = readFileSync(file, "utf8").replace(/\r\n/g, "\n") === renderExample(tool, scope);
    checks.push({ name: `renders like examples/${exampleFileName(tool, scope)}`, ok: same, detail: same ? undefined : "output changed; review and run `npm run gen:docs`" });
  }
  const age = tool.lastVerified ? Math.floor((Date.now() - Date.parse(tool.lastVerified)) / 86_400_000) : Infinity;
  checks.push({ name: "verified in the last 90 days", ok: age <= 90, detail: tool.lastVerified ?? "never" });
  return { tool: tool.id, ok: checks.every((c) => c.ok || c.name.startsWith("verified")), checks };
}

export function toolsIndexMarkdown(tools: ToolManifest[]): string {
  const rows = tools.map((t) => {
    const scopes = Object.keys(t.configs).join(", ");
    const docs = t.docs?.mcp ? `[docs](${t.docs.mcp})` : "";
    return `| [${t.name}](${t.id}/GUIDE.md) | \`${t.id}\` | ${(t.aliases ?? []).map((a) => `\`${a}\``).join(" ")} | ${t.format} | ${scopes} | ${t.status ?? "beta"} | ${t.lastVerified ?? "never"} | ${docs} |`;
  });
  return [
    "# Tools directory",
    "",
    "<!-- Generated by `npm run gen:docs` from tools/*/tool.json. Do not edit by hand. -->",
    "",
    "Every AI tool wirebay can write MCP config for. Each folder has a `tool.json` manifest,",
    "a `GUIDE.md` with setup and quirks, and `examples/` of what wirebay writes.",
    "",
    "| Tool | Id | Aliases | Format | Scopes | Status | Last verified | Official docs |",
    "|---|---|---|---|---|---|---|---|",
    ...rows,
    "",
    "Missing a tool? See [Add a tool](../docs/contributing/add-a-tool.md). It is usually just JSON and Markdown.",
    "",
  ].join("\n");
}

export function listToolDirs(): string[] {
  return readdirSync(packagePaths.tools).filter((d) => !d.startsWith("_") && existsSync(path.join(packagePaths.tools, d, "tool.json")));
}
