// Regenerates everything derived from data, so docs never drift from the code:
//   - tools/<id>/examples/<scope>.<ext>   (what wirebay writes, with {{placeholders}})
//   - tools/INDEX.md                       (tools directory table)
//   - README.md tables between <!-- generated:… --> markers
//   - docs/cli-reference.md                (from src/cli/grammar.ts + command help)
// Run: npm run gen:docs      Check only (CI): npm run gen:docs -- --check

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { FLAGS, VERBS } from "../src/cli/grammar.ts";
import { authLabel } from "../src/commands/directory.ts";
import { COMMAND_HELP } from "../src/commands/help.ts";
import { exampleFileName, renderExample, toolsIndexMarkdown } from "../src/core/directory.ts";
import { packageRoot } from "../src/core/paths.ts";
import { loadPresets } from "../src/core/servers.ts";
import { loadTools } from "../src/core/tools.ts";
import type { Launch, ScopeName, ServerDef } from "../src/core/types.ts";

export const REPO_URL = "https://github.com/VijayJaybhay/wirebay";

const check = process.argv.includes("--check");
const stale: string[] = [];

function write(file: string, content: string): void {
  const abs = path.join(packageRoot, file);
  const current = existsSync(abs) ? readFileSync(abs, "utf8").replace(/\r\n/g, "\n") : undefined;
  if (current === content) return;
  if (check) {
    stale.push(file);
    return;
  }
  mkdirSync(path.dirname(abs), { recursive: true });
  writeFileSync(abs, content);
  console.log(`wrote ${file}`);
}

function replaceBetween(text: string, marker: string, content: string): string {
  const start = `<!-- generated:${marker} -->`;
  const end = `<!-- /generated:${marker} -->`;
  const i = text.indexOf(start);
  const j = text.indexOf(end);
  if (i < 0 || j < i) return text;
  return text.slice(0, i + start.length) + "\n" + content.trim() + "\n" + text.slice(j);
}

// Tool examples and index
// Ignore any user overrides so generated files only reflect the repo.
process.env.WIREBAY_HOME = path.join(packageRoot, ".no-user-home");
const tools = loadTools().filter((t) => t.source === "package");
for (const tool of tools) {
  for (const scope of Object.keys(tool.configs) as ScopeName[]) {
    write(`tools/${tool.id}/examples/${exampleFileName(tool, scope)}`, renderExample(tool, scope));
  }
}
write("tools/INDEX.md", toolsIndexMarkdown(tools));

// Server catalog (docs/servers/catalog.md), generated from presets/*.json
const sortedPresets = [...loadPresets().values()].sort(
  (a, b) => (a.category ?? "").localeCompare(b.category ?? "") || a.name.localeCompare(b.name),
);
write("docs/servers/catalog.md", catalogMarkdown(sortedPresets));

function launchSummary(launch: Launch): string {
  if (launch.type === "remote") {
    const auth = launch.auth?.type === "oauth" ? "browser sign-in" : launch.auth && "secret" in launch.auth ? `\`${launch.auth.secret}\`` : "no auth";
    return `hosted server \`${launch.url}\` (${auth}), bridged with mcp-remote`;
  }
  const args = (launch.args ?? []).map((a) => (typeof a === "string" ? a : `[${a.optional.join(" ")}]`));
  return `\`${[launch.command, ...args].join(" ")}\``;
}

function catalogMarkdown(presets: ServerDef[]): string {
  const out = [
    "# Server catalog",
    "",
    "<!-- Generated by `npm run gen:docs` from presets/*.json. Do not edit by hand. -->",
    "",
    "Every built-in server, grouped by category. Add one with `wirebay add <name> to <tools>`.",
    "Servers marked *browser sign-in* open a login page the first time a tool starts them.",
    "Some presets have their own detailed guide: [GitHub](github.md), [Netlify](netlify.md), [Firebase](firebase.md), [AWS](aws.md).",
    "Anything not listed works too: see [custom servers](custom-servers.md).",
    "",
    "| Category | Servers |",
    "|---|---|",
  ];
  const byCategory = new Map<string, ServerDef[]>();
  for (const p of presets) byCategory.set(p.category ?? "utilities", [...(byCategory.get(p.category ?? "utilities") ?? []), p]);
  for (const [cat, list] of byCategory) out.push(`| ${cat} | ${list.map((p) => `[${p.name}](#${p.name})`).join(" · ")} |`);
  out.push("");
  for (const p of presets) {
    out.push(`## ${p.name}`, "", p.description ?? "", "");
    out.push(
      `**Category:** ${p.category ?? "utilities"} · **Status:** ${p.status ?? "beta"} · **Auth:** ${authLabel(p)} · **Verified:** ${p.lastVerified ?? "never"}${p.docs ? ` · [Official docs](${p.docs})` : ""}`,
      "",
    );
    out.push("```bash", `wirebay add ${p.name} to all`, "```", "");
    out.push(`- **Runs:** ${launchSummary(p.launch)}`);
    for (const [name, v] of Object.entries(p.variants ?? {})) out.push(`- **\`--variant ${name}\`:** ${launchSummary(v)}`);
    if (p.prereqs?.length) out.push(`- **Needs:** ${p.prereqs.join(", ")}`);
    out.push("");
    if (p.secrets?.length) {
      out.push("| Key | Required | What it is | Where to get it |", "|---|---|---|---|");
      for (const s of p.secrets) out.push(`| \`${s.key}\` | ${s.required ? "yes" : "no"} | ${s.description ?? ""} | ${s.help ? `[link](${s.help})` : ""} |`);
      out.push("", `Set with \`wirebay secrets set <KEY>\`.`, "");
    }
    for (const n of p.notes ?? []) out.push(`> ${n}`, ">");
    if (p.notes?.length) out.pop();
    out.push("");
  }
  return out.join("\n").replace(/\n{3,}/g, "\n\n");
}

// README tables
const readmePath = path.join(packageRoot, "README.md");
if (existsSync(readmePath)) {
  let readme = readFileSync(readmePath, "utf8").replace(/\r\n/g, "\n");
  const serverRows = sortedPresets.map(
    (p) => `| ${p.category ?? ""} | **${p.name}** | ${p.description ?? ""} | ${authLabel(p)} | [guide](${REPO_URL}/blob/main/${p.guide ?? "docs/servers/README.md"}) |`,
  );
  readme = replaceBetween(readme, "servers", ["| Category | Server | What it does | Auth | Guide |", "|---|---|---|---|---|", ...serverRows].join("\n"));
  const toolRows = tools.map(
    (t) =>
      `| **${t.name}** | \`${t.id}\`${(t.aliases ?? []).map((a) => ` \`${a}\``).join("")} | ${Object.keys(t.configs).join(", ")} | ${t.lastVerified ?? ""} | [guide](${REPO_URL}/blob/main/tools/${t.id}/GUIDE.md) |`,
  );
  readme = replaceBetween(readme, "tools", ["| Tool | Name in commands | Scopes | Last verified | Guide |", "|---|---|---|---|---|", ...toolRows].join("\n"));
  write("README.md", readme);
}

// CLI reference
const lines = [
  "# CLI reference",
  "",
  "<!-- Generated by `npm run gen:docs` from src/cli/grammar.ts and src/commands/help.ts. Do not edit by hand. -->",
  "",
  "Every command also accepts natural phrasing; see [command grammar](command-grammar.md).",
  "",
];
for (const [name, h] of Object.entries(COMMAND_HELP)) {
  const aliases = Object.entries(VERBS)
    .filter(([k, v]) => v === name && k !== name)
    .map(([k]) => `\`${k}\``);
  lines.push(`## \`${name}\``, "", h.summary, "", "```", h.usage, "```", "");
  if (aliases.length) lines.push(`Aliases: ${aliases.join(", ")}`, "");
  lines.push("Examples:", "", "```bash", ...h.examples, "```", "");
}
lines.push("## Options", "", "| Option | Description |", "|---|---|");
for (const f of FLAGS) lines.push(`| \`--${f.name}${f.value ? " <value>" : ""}\`${f.short ? ` / \`-${f.short}\`` : ""} | ${f.description} |`);
lines.push(
  "",
  "## Exit codes",
  "",
  "| Code | Meaning |",
  "|---|---|",
  "| 0 | Success |",
  "| 1 | Error |",
  "| 2 | Usage error (unknown command, missing argument) |",
  "| 3 | `doctor` found problems |",
  "| 4 | Conflict or hand-edited entry; re-run with `--force` to overwrite |",
  "",
);
write("docs/cli-reference.md", lines.join("\n"));

if (check && stale.length) {
  console.error(`Generated files are out of date:\n  ${stale.join("\n  ")}\nRun: npm run gen:docs`);
  process.exit(1);
}
if (check) console.log("Generated files are up to date.");
