// Regenerates everything derived from data, so docs never drift from the code:
//   - tools/<id>/examples/<scope>.<ext>   (what wirebay writes, with {{placeholders}})
//   - tools/INDEX.md                       (tools directory table)
//   - README.md tables between <!-- generated:… --> markers
//   - docs/cli-reference.md                (from src/cli/grammar.ts + command help)
// Run: npm run gen:docs      Check only (CI): npm run gen:docs -- --check

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { FLAGS, VERBS } from "../src/cli/grammar.ts";
import { COMMAND_HELP } from "../src/commands/help.ts";
import { exampleFileName, renderExample, toolsIndexMarkdown } from "../src/core/directory.ts";
import { packageRoot } from "../src/core/paths.ts";
import { loadPresets } from "../src/core/servers.ts";
import { loadTools } from "../src/core/tools.ts";
import type { ScopeName } from "../src/core/types.ts";

export const REPO_URL = "https://github.com/VijayJaybhay/wirebay";

const check = process.argv.includes("--check");
const stale: string[] = [];

function write(file: string, content: string): void {
  const abs = path.join(packageRoot, file);
  const current = existsSync(abs) ? readFileSync(abs, "utf8").replace(/\r\n/g, "\n") : undefined;
  if (current === content) return;
  if (check) {
    stale.push(file);
    return;
  }
  mkdirSync(path.dirname(abs), { recursive: true });
  writeFileSync(abs, content);
  console.log(`wrote ${file}`);
}

function replaceBetween(text: string, marker: string, content: string): string {
  const start = `<!-- generated:${marker} -->`;
  const end = `<!-- /generated:${marker} -->`;
  const i = text.indexOf(start);
  const j = text.indexOf(end);
  if (i < 0 || j < i) return text;
  return text.slice(0, i + start.length) + "\n" + content.trim() + "\n" + text.slice(j);
}

// Tool examples and index
// Ignore any user overrides so generated files only reflect the repo.
process.env.WIREBAY_HOME = path.join(packageRoot, ".no-user-home");
const tools = loadTools().filter((t) => t.source === "package");
for (const tool of tools) {
  for (const scope of Object.keys(tool.configs) as ScopeName[]) {
    write(`tools/${tool.id}/examples/${exampleFileName(tool, scope)}`, renderExample(tool, scope));
  }
}
write("tools/INDEX.md", toolsIndexMarkdown(tools));

// README tables
const readmePath = path.join(packageRoot, "README.md");
if (existsSync(readmePath)) {
  let readme = readFileSync(readmePath, "utf8").replace(/\r\n/g, "\n");
  const presets = [...loadPresets().values()].sort((a, b) => a.name.localeCompare(b.name));
  const serverRows = presets.map(
    (p) => `| **${p.name}** | ${p.description ?? ""} | \`wirebay add ${p.name} to all\` | [guide](${REPO_URL}/blob/main/${p.guide ?? "docs/servers/README.md"}) |`,
  );
  readme = replaceBetween(readme, "servers", ["| Server | What it does | Add it | Guide |", "|---|---|---|---|", ...serverRows].join("\n"));
  const toolRows = tools.map(
    (t) =>
      `| **${t.name}** | \`${t.id}\`${(t.aliases ?? []).map((a) => ` \`${a}\``).join("")} | ${Object.keys(t.configs).join(", ")} | ${t.lastVerified ?? ""} | [guide](${REPO_URL}/blob/main/tools/${t.id}/GUIDE.md) |`,
  );
  readme = replaceBetween(readme, "tools", ["| Tool | Name in commands | Scopes | Last verified | Guide |", "|---|---|---|---|---|", ...toolRows].join("\n"));
  write("README.md", readme);
}

// CLI reference
const lines = [
  "# CLI reference",
  "",
  "<!-- Generated by `npm run gen:docs` from src/cli/grammar.ts and src/commands/help.ts. Do not edit by hand. -->",
  "",
  "Every command also accepts natural phrasing; see [command grammar](command-grammar.md).",
  "",
];
for (const [name, h] of Object.entries(COMMAND_HELP)) {
  const aliases = Object.entries(VERBS)
    .filter(([k, v]) => v === name && k !== name)
    .map(([k]) => `\`${k}\``);
  lines.push(`## \`${name}\``, "", h.summary, "", "```", h.usage, "```", "");
  if (aliases.length) lines.push(`Aliases: ${aliases.join(", ")}`, "");
  lines.push("Examples:", "", "```bash", ...h.examples, "```", "");
}
lines.push("## Options", "", "| Option | Description |", "|---|---|");
for (const f of FLAGS) lines.push(`| \`--${f.name}${f.value ? " <value>" : ""}\`${f.short ? ` / \`-${f.short}\`` : ""} | ${f.description} |`);
lines.push(
  "",
  "## Exit codes",
  "",
  "| Code | Meaning |",
  "|---|---|",
  "| 0 | Success |",
  "| 1 | Error |",
  "| 2 | Usage error (unknown command, missing argument) |",
  "| 3 | `doctor` found problems |",
  "| 4 | Conflict or hand-edited entry; re-run with `--force` to overwrite |",
  "",
);
write("docs/cli-reference.md", lines.join("\n"));

if (check && stale.length) {
  console.error(`Generated files are out of date:\n  ${stale.join("\n  ")}\nRun: npm run gen:docs`);
  process.exit(1);
}
if (check) console.log("Generated files are up to date.");
